version: "3.8"
services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    volumes:
      - $PWD/db/dynamodb/data:/data
    networks:
      - sam-cli
networks:
  sam-cli:
    external: true
