name: CDK Deploy
on:
  push:
    branches:  # tags
      - 'main' # v[0-9]+.[0-9]+.[0-9]+-env

permissions:
  id-token: write
  contents: read
  actions: read

env:
  ENVIRONMENT: dev # ${{ secrets.ENVIRONMENT }}
  JWT_TOKEN: dummy # ${{ secrets.JWT_TOKEN }}

jobs:
  deploy:
    # runs-on: ['self-hosted', 'linux', 'x64']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Npm install
        run: |
          npm i -g npm
          npm ci

      - name: ITG Build Code
        run: |
          npm run build

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::632145475845:role/be-deploy-role
          role-session-name: deploy-role-session
          aws-region: ap-northeast-1

      - run: aws sts get-caller-identity

      - run: npm run cdk:deploy
